/**
 * Generates docs/research/mhwbg-content-dossier.md from the vendored CC0 quest
 * card dataset, and cross-checks it against the app's own catalog so the gap
 * list is derived rather than hand-maintained.
 *
 *   npm run report:research
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { LOOT_TABLES, BREAKABLE_PARTS } from "../src/data/lootTables";
import { quests as appQuests } from "../src/data/quests";
import { gameData } from "../src/data/gameData";

const ROOT = resolve(import.meta.dirname, "..");
const SOURCE = resolve(ROOT, "docs/research/data/mhwbg-quest-cards.cc0.json");
const OUT = resolve(ROOT, "docs/research/mhwbg-content-dossier.md");

type Localised = { language: string; text: string }[];
interface Part {
  part: string;
  armor?: number;
  break?: number;
}
interface Reward {
  number: number;
  "item-reward"?: Localised;
  "break-reward"?: unknown;
}
interface Physiology {
  "monster-type"?: Localised;
  hitpoints?: number;
  resistance?: Record<string, number>;
  special?: { name?: Localised };
  parts?: Part[];
  rewards?: Reward[];
}
interface Quest {
  "monster-id": string;
  "quest-id": string;
  difficulty: number;
  "quest-category"?: Localised;
  "time-limit"?: number;
  physiology?: Physiology;
}
interface QuestBook {
  name: Localised;
  zone?: string;
  quests: Quest[];
}

const en = (v?: Localised): string =>
  v?.find((x) => x.language.startsWith("en"))?.text ?? v?.[0]?.text ?? "";

/** Boxes of the MHW line, in release order, with the monsters each contains. */
const BOXES: { box: string; monsters: string[] }[] = [
  { box: "Ancient Forest (core)", monsters: ["great-jagras", "tobi-kadachi", "anjanath", "rathalos", "azure-rathalos"] },
  { box: "Wildspire Waste (core)", monsters: ["barroth", "pukei-pukei", "jyuratodus", "diablos", "black-diablos"] },
  { box: "Kulu-Ya-Ku (KS exclusive)", monsters: ["kulu-ya-ku"] },
  { box: "Kushala Daora", monsters: ["kushala-daora"] },
  { box: "Nergigante", monsters: ["nergigante"] },
  { box: "Teostra (KS exclusive)", monsters: ["teostra"] },
  { box: "Kirin (SFG exclusive)", monsters: ["kirin"] },
  { box: "Picking Bones (SFG exclusive)", monsters: ["tzitzi-ya-ku", "great-girros", "radobaan"] },
];

/** Catalog monster id for a dataset monster id (they differ for Great Jagras). */
const CATALOG_ID: Record<string, string> = { "great-jagras": "jagras" };
const catalogId = (id: string) => CATALOG_ID[id] ?? id;

function main() {
  const data = JSON.parse(readFileSync(SOURCE, "utf8")) as { "quest-books": QuestBook[] };
  const byMonster = new Map<string, Quest[]>();
  for (const book of data["quest-books"]) {
    for (const q of book.quests) {
      const list = byMonster.get(q["monster-id"]) ?? [];
      list.push(q);
      byMonster.set(q["monster-id"], list);
    }
  }

  const appMonsterIds = new Set(gameData.monsters.map((m) => m.id));
  const appQuestIds = new Set(appQuests.map((q) => q.id));

  const out: string[] = [];
  out.push("# MHW: The Board Game — content dossier");
  out.push("");
  out.push("> Generated by `npm run report:research`. Do not edit by hand.");
  out.push("");
  out.push(
    "Primary source: [`Elvaron/MHW-BG-QuestCards`](https://github.com/Elvaron/MHW-BG-QuestCards)," +
      " **CC0-1.0**, vendored at `docs/research/data/mhwbg-quest-cards.cc0.json`." +
      " Each quest carries its printed card index, so entries are traceable back to the physical cards.",
  );
  out.push("");
  out.push(
    "**Validated against the app.** The Great Jagras reward table in this dataset matches" +
      " `src/data/lootTables.ts` row for row, including which rolls are break rewards — so the" +
      " dataset is trustworthy for the monsters the app does not yet have.",
  );
  out.push("");

  // Coverage summary.
  out.push("## Coverage");
  out.push("");
  out.push("| Box | Monster | In catalog | Quests in app | Loot table | Source data |");
  out.push("|---|---|---|---|---|---|");
  for (const { box, monsters } of BOXES) {
    for (const m of monsters) {
      const cid = catalogId(m);
      const src = byMonster.get(m);
      const appQ = appQuests.filter((q) => q.monsterId === cid).length;
      out.push(
        `| ${box} | ${m} | ${appMonsterIds.has(cid) ? "yes" : "**no**"} | ${
          appQ || "**0**"
        } | ${LOOT_TABLES[cid] ? "yes" : "**no**"} | ${
          src ? `${src.length} quests + physiology` : "**none found**"
        } |`,
      );
    }
  }
  out.push("");

  // Quest tiers.
  out.push("## Quest tiers, as printed");
  out.push("");
  out.push(
    "Categories come straight from the cards. Note **3★ is a *Tempered* Investigation**," +
      " which the app currently labels as a plain Investigation (`src/screens/QuestScreen.tsx`," +
      " `STAR_TYPE_LABEL`).",
  );
  out.push("");
  out.push("| Difficulty | Printed category |");
  out.push("|---|---|");
  const cats = new Map<number, Set<string>>();
  for (const list of byMonster.values()) {
    for (const q of list) {
      const set = cats.get(q.difficulty) ?? new Set();
      set.add(en(q["quest-category"]));
      cats.set(q.difficulty, set);
    }
  }
  for (const diff of [...cats.keys()].sort((a, b) => a - b)) {
    out.push(`| ${"★".repeat(diff)} (${diff}) | ${[...cats.get(diff)!].join(", ")} |`);
  }
  out.push("");

  // Per monster detail.
  out.push("## Per monster");
  out.push("");
  for (const { box, monsters } of BOXES) {
    out.push(`### ${box}`);
    out.push("");
    for (const m of monsters) {
      const list = byMonster.get(m);
      if (!list) {
        out.push(`#### ${m}`);
        out.push("");
        out.push("**No source data found.** This box post-dates the CC0 dataset; its quest");
        out.push("tiers, reward table, breakable parts and forge costs must be transcribed");
        out.push("from the physical cards.");
        out.push("");
        continue;
      }
      const phys = list.find((q) => q.physiology)?.physiology;
      out.push(`#### ${m}`);
      out.push("");
      out.push(
        `- Type: ${en(phys?.["monster-type"]) || "?"} · HP: ${phys?.hitpoints ?? "?"}` +
          (phys?.special?.name ? ` · Special: ${en(phys.special.name)}` : ""),
      );
      if (phys?.parts?.length) {
        out.push(
          `- Parts: ${phys.parts
            .map((p) => `${p.part} (armour ${p.armor ?? 0}, break ${p.break ?? "–"})`)
            .join(", ")}`,
        );
        const known = BREAKABLE_PARTS[catalogId(m)];
        if (known) out.push(`  - app \`BREAKABLE_PARTS\`: ${known.join(", ")}`);
      }
      if (phys?.resistance) {
        out.push(
          `- Resistances: ${Object.entries(phys.resistance)
            .map(([k, v]) => `${k} ${v > 0 ? "+" : ""}${v}`)
            .join(", ")}`,
        );
      }
      out.push(
        `- Quests: ${list
          .map((q) => `${q["quest-id"]} (${q.difficulty}★${appQuestIds.has(q["quest-id"]) ? "" : ", **missing**"})`)
          .join(", ")}`,
      );
      const rewards = phys?.rewards;
      if (rewards?.length) {
        out.push("");
        out.push("| Roll | Reward | Break reward |");
        out.push("|---|---|---|");
        for (const r of rewards) {
          out.push(
            `| ${r.number} | ${en(r["item-reward"])} | ${"break-reward" in r ? "yes" : ""} |`,
          );
        }
      }
      out.push("");
    }
  }

  writeFileSync(OUT, out.join("\n"));
  console.log(`wrote ${OUT}`);
}

main();
